cmake_minimum_required(VERSION 4.2)
project(Leetcode)

set(CMAKE_CXX_STANDARD 14)

add_executable(Leetcode
        14.cpp
        20.cpp
        26.cpp
        27.cpp
        28.cpp
        32.cpp
        33.cpp
        34.cpp
        37.cpp
        38.cpp
        39.cpp
        40.cpp
        41.cpp
        42.cpp
        "45 - Jump Game II.cpp"
        "51 - N-queen.cpp"
        "52 - N-queen II.cpp"
        "53 - Maximum Subarray.cpp")
